In [10]:
import numpy as np
import torch

In [2]:
from imp import reload

In [3]:
from models import SeqLabeling

In [141]:
reload(SeqLabeling)
SeqLab = SeqLabeling.RNNModel
model = SeqLab(10,3,dropout=0)

In [33]:
a = np.array([1,1,2,2,3,3,4,4,5,5])
print(len(a))

10


In [34]:
a = a.reshape(5,-1)
print(a.shape)
print(a)

(5, 2)
[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]


In [69]:
b = torch.from_numpy(a)

In [146]:
reload(SeqLabeling)
SeqLab = SeqLabeling.RNNModel
model = SeqLab(10,3,dropout=0)

In [147]:
o = model(b,[5,5])

In [148]:
print(o[0])

tensor([[ 0.0248,  0.0247, -0.0927],
        [ 0.0248,  0.0247, -0.0927]], grad_fn=<AddmmBackward>)


In [149]:
print(o[1])

tensor([[0.3461, 0.3461, 0.3078],
        [0.3461, 0.3461, 0.3078]], grad_fn=<SoftmaxBackward>)


In [136]:
print(o[1].shape)

torch.Size([2, 3])


In [81]:
print(o[1])

tensor([[[-0.0079, -0.0099,  0.0139],
         [-0.0079, -0.0099,  0.0139]],

        [[-0.0587, -0.0216,  0.0098],
         [-0.0587, -0.0216,  0.0098]],

        [[-0.0438, -0.0190,  0.0128],
         [ 0.0000,  0.0000,  0.0000]],

        [[-0.0634, -0.0088,  0.0045],
         [ 0.0000,  0.0000,  0.0000]],

        [[-0.0686,  0.0155,  0.0088],
         [ 0.0000,  0.0000,  0.0000]]], grad_fn=<ViewBackward>)


In [18]:
a = a.reshape()
print(a.shape)

(10,)
